default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i + ENV.fetch("GOOD_JOB_MAX_THREADS") { 5 }.to_i %>
development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>_test
production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
  username: deploy
  password:
