source "https://rubygems.org"

gem "rails", "8.1.3.1"
gem "pg", "1.6.3"
gem "puma", "8.0.2"
gem "good_job", "4.19.2"
gem "bootsnap", "1.24.6"
gem "ostruct", "0.6.3"
gem "timeout", "0.6.1"
gem "solid_errors", "0.7.0"

group :development, :test do
  gem "annotaterb", "4.24.0"
  gem "mocha", "3.1.0"
  gem "test_safety", "0.0.0", path: "../gems/test_safety", require: false
  gem "webmock", "3.26.2"
  gem "vernier", "1.10.1"
  gem "profile-viewer", "0.0.7"
end
