source "https://rubygems.org"

gem "rails"
gem "pg"
gem "puma"
gem "solid_cache"
gem "good_job"
gem "bcrypt"
gem "bootsnap"
gem "thruster"
gem "faraday"
gem "addressable"
gem "ostruct"
gem "jwt"
gem "dry-schema"
gem "aws-sdk-s3"
gem "rexml"
gem "timeout"
gem "csv"
gem "sentry-ruby"
gem "sentry-rails"
gem "xmlrpc"
gem "faraday-follow_redirects"
gem "bencode"
gem "chronic"
gem "path", path: "../gems/path"
gem "with_advisory_lock"
gem 'openssl'
gem 'resend'
gem 'ruby_llm'

group :development, :test do
  gem "pry"
  gem "rubocop"
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-minitest", require: false
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "annotaterb"
  gem "ruby-lsp"
  gem "mocha"
  gem "webmock"
  gem "pgreset"
  gem "vernier"
  gem "profile-viewer"
end
